In [1]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [3]:
df = pd.read_excel("/Users/bowiechuang/Downloads/Expedia_hotel_dataset.xlsx")
df = df.drop('hotel_details', axis = 1)
df

,hotel_name,hotel_price,hotel_city,hotel_rating,hotel_review,Number_review,start_date,end_date,Breakfast,Pool,Hottub,Per_Night_Fee,Kitchen,Washer_Dryer
0,"Drift Santa Barbara, a Member of Design Hotels",757,Santa Barbara,Ad,Very Good,300 reviews,2024-09-01,2024-09-03,NaN,NaN,NaN,$332 per night,NaN,NaN
1,"The Leta Santa Barbara Goleta, Tapestry Collec...",509,Goleta,Ad,Excellent,557 reviews,2024-09-01,2024-09-03,NaN,Pool,NaN,$219 per night,NaN,NaN
2,"Brisas del Mar, Inn at the Beach",759,Santa Barbara,9.6,Exceptional,"1,179 reviews",2024-09-01,2024-09-03,Breakfast,Pool,Hot tub,$333 per night,NaN,NaN
3,Lavender Inn by the Sea,698,Santa Barbara,9.4,Exceptional,"1,287 reviews",2024-09-01,2024-09-03,Breakfast,Pool,NaN,$306 per night,NaN,NaN
4,"West Beach Inn, a Coast Hotel",762,Santa Barbara,9.4,Exceptional,"1,003 reviews",2024-09-01,2024-09-03,Breakfast,Pool,NaN,$334 per night,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10045,Fabulous Studio/Suite With Private Entrance,408,Entire apartment,9.6,Exceptional,25 reviews,2025-08-29,2025-08-31,NaN,NaN,NaN,$204 per night,Kitchen,Washer and dryer
10046,Agave Inn,775,Santa Barbara,8.8,Excellent,636 reviews,2025-08-29,2025-08-31,NaN,NaN,NaN,$340 per night,NaN,NaN
10047,The Eagle Inn,1045,Santa Barbara,9.4,Exceptional,"1,002 reviews",2025-08-29,2025-08-31,Breakfast,NaN,NaN,$458 per night,NaN,NaN
10048,"Ocean, Sunset, Mountain Views, Private Deck: V...",910,Entire apartment,10,Exceptional,104 reviews,2025-08-29,2025-08-31,NaN,NaN,NaN,$414 per night,Kitchen,Washer and dryer
10049,Ojai Retreat & Inn,348,Ojai,9.4,Exceptional,272 reviews,2025-08-29,2025-08-31,Breakfast,NaN,NaN,$161 per night,NaN,NaN

In [10]:
pattern = r'(Santa Barbara|Goleta|Solvang|Los Olivos|Buellton|Montecito|Carpinteria|Santa Ynez|Los Alamos|Lompoc|Ojai|Ventura)'
df['hotel_city'] = df['hotel_city'].str.extract(pattern, flags = re.IGNORECASE)
df['hotel_city'] = df['hotel_city'].fillna("No City Name")

df['month'] = df['start_date'].dt.month
df['day'] = df['start_date'].dt.day
df['day_of_week'] = df['start_date'].dt.strftime("%A")

#f['Per_Night_Fee'] = df['Per_Night_Fee'].str.replace("\D", '', regex = True)
df['Per_Night_Fee'] = pd.to_numeric(df['Per_Night_Fee'], errors = 'coerce')

df['hotel_rating'] = pd.to_numeric(df['hotel_rating'], errors = 'coerce')

month_to_season = {
    1: 'Winter', 2: 'Winter', 3: 'Spring',
    4: 'Spring', 5: 'Spring', 6: 'Summer',
    7: 'Summer', 8: 'Summer', 9: 'Fall',
    10: 'Fall', 11: 'Fall', 12: 'Winter'
}
df['Season'] = df['month'].map(month_to_season)
df

,hotel_name,hotel_price,hotel_city,hotel_rating,hotel_review,Number_review,start_date,end_date,Breakfast,Pool,Hottub,Per_Night_Fee,Kitchen,Washer_Dryer,month,day,day_of_week,Season
0,"Drift Santa Barbara, a Member of Design Hotels",757,Santa Barbara,NaN,Very Good,300 reviews,2024-09-01,2024-09-03,NaN,NaN,NaN,332.0,NaN,NaN,9,1,Sunday,Fall
1,"The Leta Santa Barbara Goleta, Tapestry Collec...",509,Goleta,NaN,Excellent,557 reviews,2024-09-01,2024-09-03,NaN,Pool,NaN,219.0,NaN,NaN,9,1,Sunday,Fall
2,"Brisas del Mar, Inn at the Beach",759,Santa Barbara,9.6,Exceptional,"1,179 reviews",2024-09-01,2024-09-03,Breakfast,Pool,Hot tub,333.0,NaN,NaN,9,1,Sunday,Fall
3,Lavender Inn by the Sea,698,Santa Barbara,9.4,Exceptional,"1,287 reviews",2024-09-01,2024-09-03,Breakfast,Pool,NaN,306.0,NaN,NaN,9,1,Sunday,Fall
4,"West Beach Inn, a Coast Hotel",762,Santa Barbara,9.4,Exceptional,"1,003 reviews",2024-09-01,2024-09-03,Breakfast,Pool,NaN,334.0,NaN,NaN,9,1,Sunday,Fall
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10045,Fabulous Studio/Suite With Private Entrance,408,No City Name,9.6,Exceptional,25 reviews,2025-08-29,2025-08-31,NaN,NaN,NaN,204.0,Kitchen,Washer and dryer,8,29,Friday,Summer
10046,Agave Inn,775,Santa Barbara,8.8,Excellent,636 reviews,2025-08-29,2025-08-31,NaN,NaN,NaN,340.0,NaN,NaN,8,29,Friday,Summer
10047,The Eagle Inn,1045,Santa Barbara,9.4,Exceptional,"1,002 reviews",2025-08-29,2025-08-31,Breakfast,NaN,NaN,458.0,NaN,NaN,8,29,Friday,Summer
10048,"Ocean, Sunset, Mountain Views, Private Deck: V...",910,No City Name,10.0,Exceptional,104 reviews,2025-08-29,2025-08-31,NaN,NaN,NaN,414.0,Kitchen,Washer and dryer,8,29,Friday,Summer
10049,Ojai Retreat & Inn,348,Ojai,9.4,Exceptional,272 reviews,2025-08-29,2025-08-31,Breakfast,NaN,NaN,161.0,NaN,NaN,8,29,Friday,Summer

In [11]:
df.to_excel("/Users/bowiechuang/Downloads/Expedia_hotel_dataset_clean.xlsx")